export const FETCH_COURSES = 'FETCH_COURSES';
export const FETCH_COURSES_SUCCESS = 'FETCH_COURSES_SUCCESS';
export const FETCH_COURSES_FAILURE = 'FETCH_COURSES_FAILURE';

export const SUBMIT_ENQUIRY = 'SUBMIT_ENQUIRY';
export const SUBMIT_ENQUIRY_SUCCESS = 'SUBMIT_ENQUIRY_SUCCESS';
export const SUBMIT_ENQUIRY_FAILURE = 'SUBMIT_ENQUIRY_FAILURE';

export const FETCH_ENQUIRIES = 'FETCH_ENQUIRIES';
export const FETCH_ENQUIRIES_SUCCESS = 'FETCH_ENQUIRIES_SUCCESS';
export const FETCH_ENQUIRIES_FAILURE = 'FETCH_ENQUIRIES_FAILURE';

export const SET_SELECTED_COURSE = 'SET_SELECTED_COURSE';
export const CLEAR_SELECTED_COURSE = 'CLEAR_SELECTED_COURSE';